site_name: Mass Spec Coronavirus Public Data
nav:
    - Introduction: index.md
    - Metabolomics: metabolomics.md
    - Proteomics: proteomics.md
theme:
    name: material
#google_analytics: ['UA-8412213-5', 'ccms-ucsd.github.io']
